version: '3.8'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - ~/data/mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - my-network
    # healthcheck:
    #   test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 10
  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - ~/data/wp:/var/www/html
    ports:
      - 443:443
    env_file:
      - .env
    networks:
      - my-network
    depends_on:
      - wordpress
  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - ~/data/wp:/var/www/html
    env_file:
      - .env
    ports:
      - 9000:9000
    networks:
      - my-network
    depends_on:
      - mariadb
      # mariadb:
      #   condition: service_healthy
  adminer:
    image: adminer
    container_name: adminer
    build: ./requirements/bonus/adminer
    volumes:
      - ~/data/mariadb:/var/lib/mysql
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - my-network
    depends_on:
      - mariadb
  redis:
    image: redis
    container_name: redis
    build: ./requirements/bonus/redis
    volumes:
      - ~/data/wp:/var/www/html
    env_file:
      - .env
    networks:
      - my-network
    depends_on:
      - wordpress
  ftp:
    image: ftp
    container_name: ftp
    build: ./requirements/bonus/ftp
    volumes:
      - ~/data/wp:/var/ftp
    env_file:
      - .env
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    networks:
      - my-network
    depends_on:
      - wordpress


networks:
  my-network:
    name: my-network
    driver: bridge
