version: '3.8'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb-volume:/var/lib/mysql
    env_file:
      - .env
    networks:
      - my-network
    restart: always
  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - wp-volume:/var/www/html
    ports:
      - 443:443
    env_file:
      - .env
    networks:
      - my-network
    depends_on:
      - wordpress
    restart: always
  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wp-volume:/var/www/html
    env_file:
      - .env
    networks:
      - my-network
    depends_on:
      - mariadb
    restart: always
  adminer:
    image: adminer
    container_name: adminer
    build: ./requirements/bonus/adminer
    volumes:
      - mariadb-volume:/var/lib/mysql
    env_file:
      - .env
    ports:
      - 9090:9090
    networks:
      - my-network
    depends_on:
      - mariadb
    restart: always
  redis:
    image: redis
    container_name: redis
    build: ./requirements/bonus/redis
    volumes:
      - wp-volume:/var/www/html
    env_file:
      - .env
    networks:
      - my-network
    depends_on:
      - wordpress
  ftp:
    image: ftp
    container_name: ftp
    build: ./requirements/bonus/ftp
    volumes:
      - wp-volume:/var/www/html
    env_file:
      - .env
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    networks:
      - my-network
    depends_on:
      - wordpress
    restart: always
  cadvisor:
    container_name: cadvisor
    build: ./requirements/bonus/cadvisor
    image: cadvisor
    ports:
      - "8080:8080"
    networks:
      - my-network
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always
  static:
    container_name: static
    build: ./requirements/bonus/static
    image: static
    ports:
      - "80:80"
    networks:
      - my-network
    restart: always

networks:
  my-network:
    name: my-network
    driver: bridge

volumes:
  wp-volume:
    name: wp-volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rafiq/data/wp 
  mariadb-volume:
    name: mariadb-volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rafiq/data/mariadb
